// client/React-Components/editor.d/editor.js
const DocTitle = require('./editor-elements/title.js');
const DocumentPage = require('./editor-elements/document-page.js');


class Editor extends React.Component {
    constructor(props)
    {
        super(props);
        let document = this.props.document;
        this.state = {document: this.props.document};

        this.updateContent = this.updateContent.bind(this);
        this.addNewElementToDocument = this.addNewElementToDocument.bind(this);
    }

    updateContent(documentUpdateEvent)
    {
        if (this.props.onDocumentChange)
        {
            documentUpdateEvent.documentId = this.state.document.id;
            this.props.onDocumentChange(documentUpdateEvent);
        }
    }

    addNewElementToDocument(event)
    {

        const documentUpdateEvent = {documentId: this.state.document.id, type: 'elementCreated', element: {type: 'p', content: ''}}
        this.updateContent(documentUpdateEvent);
        /*
        this.setState( (state, props) => {
            let documentElements = this.state.document.contentElements;
            elements.push({type: 'p'});
            return { documentElements: documentElements };
        });
         */
    }
    render()
    {
        let document = this.props.document;
        return (
            <div id="editor" className="container-fluid px-0">
                <div className="offset-1 col-11 bg-white shadow w-100 vh-100 px-3 pt-2 border rounded" >
                    <div className="container">
                        <DocTitle sectionTitle={document.section}> {document.title} </DocTitle>
                        <DocumentPage documentId={document.id} documentChildren={document.contentElements} onDocumentChange={this.updateContent}/>
                        <button className="btn btn-sm btn-outline-light text-muted border-0" href="#" onClick={this.addNewElementToDocument}>
                            <span className="material-icons align-middle py-1">vertical_align_top</span>
                            Add New Item
                        </button>
                    </div>
                </div>
            </div>
        )
    }
}

module.exports = Editor;

// Client/Views/Editor.vue
<template>
    <div id="editor-container" class="col-9">
        <div id="editor" class="container bg-white shadow w-100 vh-100 px-4 pt-2 border rounded">
            <header class="mt-5 px-3 py-3 pb-1  display-4" style="font-size: 25px" >
                <span class="text-muted"> {{sectionTitle}} / </span>
                <span class="" contentEditable> {{page.title}} </span>
                <hr />
            </header>

            <div class="m-5">
                <div v-for="element in page.elements">
                    <PageElement v-bind:element="element" />
                </div>
                <button class="btn btn-sm btn-outline-light text-muted border-0 ml-5" href="#"
                    v-on:click="addNewElementToPage">
                    <span class="material-icons align-middle py-1">vertical_align_top</span>
                    Add New Element
                </button>
            </div>
        </div>
    </div>
</template>

<script>
    import PageElement from './EditorViews/PageElement.vue';

    export default {
        props: ['page', 'section-title', 'onAddNewElementClick'],
        methods: {
            addNewElementToPage: function() {
                this.page.appendNewElement()
            }
        },
        components: {
            PageElement: PageElement
        }
    };
</script>
